{
 "title": "Metrics Dummy",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(envoy_cluster_upstream_cx_rx_bytes_total, consul_source_service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RX bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_cx_rx_bytes_total{consul_destination_service=\"$service\",consul_source_service!=\"\"}[$__rate_interval])",
     "legendFormat": "{{ consul_source_service }} --> {{ consul_destination_service }}"
    }
   ]
  },
  {
   "title": "TX bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_cx_tx_bytes_total{consul_source_service=\"$service\",consul_destination_service!=\"\"}[$__rate_interval])",
     "legendFormat": "{{ consul_source_service }} <-- {{ consul_service }}"
    }
   ]
  },
  {
   "title": "RX latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_http_downstream_rq_time_bucket{consul_source_service=\"$service\",envoy_http_conn_manager_prefix=\"public_listener\"}[$__rate_interval])) by (le))"
    }
   ]
  },
  {
   "title": "TX latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{consul_source_service=\"$service\"}[$__rate_interval])) by (le))"
    }
   ]
  }
 ]
}