apiVersion: 1
datasources:
  - basicAuth: false
    isDefault: true
    jsonData:
      timeInterval: 15s
    name: Prometheus
    type: prometheus
    url: "http://172.17.0.1:9090"
  - basicAuth: false
    isDefault: false
    jsonData:
      maxLines: 1000
    name: Loki
    type: loki
    url: "http://172.17.0.1:3100"
